### ISSUE TITLE
add newline between harness output and user output

### ISSUE THREAD

**Issue by ORESoftware** [sumanjs/suman#300]
The following:

```
       [1] ✔ 'passes' (109ms)
       [2] ✔ 'passes' (110ms)
        stderr for 2: assert.js:337
        stderr for 2:     throw err;
        stderr for 2:     ^
        stderr for 2: 
        stderr for 2: AssertionError [ERR_ASSERTION]: "short" letter must be alphabetic (uppercase or lowercase.
        stderr for 2:     at new CliParser (/home/oleg/WebstormProjects/oresoftware/cli.ts/dist/index.js:40:17)
        stderr for 2:     at Object.<anonymous> (/home/oleg/WebstormProjects/oresoftware/cli.ts/test/fixtures/script1.js:11:11)
        stderr for 2:     at Module._compile (internal/modules/cjs/loader.js:689:30)
        stderr for 2:     at startup (internal/bootstrap/node.js:266:19)
        stderr for 2:     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
       [3] ✔ 'passes' (114ms)

````

should look like this instead:

```
       [1] ✔ 'passes' (109ms)
       [2] ✔ 'passes' (110ms)

        stderr for 2: assert.js:337
        stderr for 2:     throw err;
        stderr for 2:     ^
        stderr for 2: 
        stderr for 2: AssertionError [ERR_ASSERTION]: "short" letter must be alphabetic (uppercase or lowercase.
        stderr for 2:     at new CliParser (/home/oleg/WebstormProjects/oresoftware/cli.ts/dist/index.js:40:17)
        stderr for 2:     at Object.<anonymous> (/home/oleg/WebstormProjects/oresoftware/cli.ts/test/fixtures/script1.js:11:11)
        stderr for 2:     at Module._compile (internal/modules/cjs/loader.js:689:30)
        stderr for 2:     at startup (internal/bootstrap/node.js:266:19)
        stderr for 2:     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

       [3] ✔ 'passes' (114ms)

```

**Comment by ORESoftware** [comment]
accomplish this by patching `process.stdout.write` and `process.stderr.write`, obviously
